steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "front"
    id: "front:install_dep"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build-prod"]
    dir: "front"
    id: "front:build"
    waitFor: ["front:install_dep"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy"]
    waitFor: ["front:build"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
    timeout: '1600s'
