/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Mizuoka Generator API
 * Generate Mizuoka face picture with a quote.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface GenerateRequest
 */
export interface GenerateRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateRequest
     */
    text: string;
}
/**
 * 
 * @export
 * @interface GenerateResponse
 */
export interface GenerateResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerateResponse
     */
    text: string;
}
/**
 * GenerateApi - fetch parameter creator
 * @export
 */
export const GenerateApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate Mizuoka face picture with a quote.
         * @summary Generate Mizuoka face picture with a quote
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePost(text?: string, options: any = {}): FetchArgs {
            const localVarPath = `/generate`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new url.URLSearchParams();

            if (text !== undefined) {
                localVarFormParams.set('text', text as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GenerateApi - functional programming interface
 * @export
 */
export const GenerateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Generate Mizuoka face picture with a quote.
         * @summary Generate Mizuoka face picture with a quote
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePost(text?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GenerateResponse> {
            const localVarFetchArgs = GenerateApiFetchParamCreator(configuration).generatePost(text, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * GenerateApi - factory interface
 * @export
 */
export const GenerateApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Generate Mizuoka face picture with a quote.
         * @summary Generate Mizuoka face picture with a quote
         * @param {string} [text] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePost(text?: string, options?: any) {
            return GenerateApiFp(configuration).generatePost(text, options)(fetch, basePath);
        },
    };
};

/**
 * GenerateApi - object-oriented interface
 * @export
 * @class GenerateApi
 * @extends {BaseAPI}
 */
export class GenerateApi extends BaseAPI {
    /**
     * Generate Mizuoka face picture with a quote.
     * @summary Generate Mizuoka face picture with a quote
     * @param {string} [text] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenerateApi
     */
    public generatePost(text?: string, options?: any) {
        return GenerateApiFp(this.configuration).generatePost(text, options)(this.fetch, this.basePath);
    }

}
