/**
 * Mizuoka Generator API
 * Generate Mizuoka face picture with a quote.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("GenerateApi", () => {
  let instance: api.GenerateApi
  beforeEach(function() {
    instance = new api.GenerateApi(config)
  });

  test("generatePost", () => {
    const text: string = "text_example"
    return expect(instance.generatePost(text, {})).resolves.toBe(null)
  })
})

