openapi: 3.0.0
info:
  title: Mizuoka Generator API
  description: Generate Mizuoka face picture with a quote.
  version: 1.0.0
paths:
  /generate:
    post:
      tags:
        - Generate
      summary: Generate Mizuoka face picture with a quote
      description: Generate Mizuoka face picture with a quote.
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '200':
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GenerateResponse'
        '500':
          description: Internal Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GenerateResponse'
components:
  schemas:
    GenerateRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
    GenerateResponse:
      type: object
      required:
        - location
      properties:
        location:
          type: string
